### ISSUE TITLE
location.thoughtbot.com returning wrong address

### ISSUE THREAD

**Issue by AdrianRogowski** [thoughtbot/location#3]
First noticed while viewing blogs on https://robots.thoughtbot.com

Expected behavior on the blog is to have a CTA button directing you to the nearest thoughtbot office if you are within 20km

I am located in the thoughtbot Boston office and right now https://location.thoughtbot.com/v1/nearest is returning the following which means I do not get a link to the Boston location page.

IP address: 74.92.13.241
ISP: Comcast Business
City: Boston, Massachusetts

`{"meta":{"distanceKmToUser":832.0374118116138},"name":"Austin","slug":"austin","url":"https://thoughtbot.com/austin"}`

Additionally the I'm also blocked from seeing the CTA on Verizon LTE while at the office since it's registering as over 20km away.

IP address: 2600:1000:b008:3dd9:ec:5d54:e4d9:6aa0
ISP: Verizon Wireless
City: Brighton, Massachusetts

`{"meta":{"distanceKmToUser":30.37991679606413},"name":"Boston","slug":"boston","url":"https://thoughtbot.com/boston"}`

**Comment by mjankowski** [comment]
@AdrianRogowski can you confirm whether this is still the case?

I'm going to close this issue because we don't really have control over this - and have to rely on an underlying data dump (which we updated periodically), so there's not much to do here to resolve even if we wanted to.
